name: Engineering build
on: push

env:
  DIST: el9
  ARCH: x86_64
  RPMNAME: os-discovery-tool

jobs:
    build_tarball:
        name: Build source archive
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Replace version in source files
              run: sed -Ei 's/@@RPM_VERSION@@$/${{github.run_number}}/' gather_inventory_from_host.sh

            - name: Replace version in RPM spec so correct source is downloaded when building RPM
              run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{github.run_number}}/' ${{ github.event.repository.name }}.spec

            - name: Create source archive
              run: tar -cvf ${{ env.RPMNAME }}-${{ github.run_number }}.tar.gz *

            - name: Upload source archive as artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.RPMNAME }}-${{ github.run_number }}.tar.gz
                path: ${{ env.RPMNAME }}-${{ github.run_number }}.tar.gz

    build_rpm:
        name: Build .rpm package
        needs: build_tarball
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Replace version in RPM spec so correct source is downloaded when building RPM
              run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{github.run_number}}/' ${{ github.event.repository.name }}.spec

            - name: Run rpmbuild on RPM spec to produce package
              id: rpm
              uses: naveenrajm7/rpmbuild@master
              with:
                spec_file: ${{ github.event.repository.name }}.spec

            - name: Upload .rpm package as artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.RPMNAME }}-${{ github.run_number }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
                path: rpmbuild/RPMS/${{ env.ARCH }}/*.rpm

    build_deb:
        name: Build .deb package
        needs: build_rpm
        runs-on: ubuntu-latest
        steps:
            - name: Download .rpm artifact
              uses: actions/download-artifact@v4
              id: download
              with:
                name: ${{ env.RPMNAME }}-${{ github.run_number }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm

            - name: find .
              run: find .

            - name: Convert .rpm to .deb
              run: |
                sudo apt install -y alien
                sudo alien -k --verbose --scripts --to-deb *.rpm

            - name: find .
              run: find . -exec readlink -f {} \;

            - name: Upload .deb package as artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.RPMNAME }}-${{ github.run_number }}-1.${{ env.DIST }}.${{ env.ARCH }}.deb
                path: ${{ env.RPMNAME }}*.deb
